database:
  in_use: false
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password:
  name:
  table_prefix:
  charset: utf8
  file: var/local.db

mailer:
  in_use: false
  address:
  password:
  host:
  encryption: tls # tls, ssl, none
  port: 587

site:
  title:
  key:  # basically an api key for your project
  user_agent: 'Custom UserAgent'
  default_locale: en

features:
  google_analytics: false
  matomo: false
  cookie_consent: false

session:
  name: PROJECTSESSID
  
cookie:
  login_attempt: LA
  language: LANG
